export type Guide = { slug: string; title: string; read: string; img: string; ph: string; intro: string; assess: string; sections: [string, string][]; faqs: [string, string][] };

// General education written for owners of established Indian businesses. Keep it to
// well-established practice; no statistics or legal citations that cannot be sourced.
export const GUIDE_AUTHOR = 'Karan Bindal';
export const GUIDE_PUBLISHED = '2026-10-05';

export const GUIDES: Guide[] = [
  { slug: 'family-business-succession', title: 'Family business succession', read: '7 min read', img: '/images/guide-family.jpg', ph: 'Two generations at the family business', intro: 'Handing the business to the next generation is the most common intention among Indian owners, and often the least planned.', assess: 'Successor readiness and owner dependency are scored separately, so you can see whether the gap is in the person, the business, or both.', sections: [
    ['Start with a real conversation, not an assumption', 'Many successors have never been asked directly. Ask what they want, what they fear and what they would change. Interest, capability and timing are three separate questions; a yes to one is not a yes to all. Give them room to say no without it becoming a family crisis.'],
    ['Separate ownership from management', 'A child can own shares without running the business, or run it without owning it yet. Decide both deliberately. A shareholder agreement covers voting, dividends and what happens if someone wants out, and a short family charter sets how family members join, are paid and are reviewed. Both are easier to agree before anyone is under pressure.'],
    ['Prepare the business, not just the person', 'If customers, suppliers and the bank deal only with you, a successor inherits a title but not the relationships. Transfer them over two to three years, one at a time, while you are still there to repair mistakes. Introduce the successor in person and then step out of the conversation.'],
    ['Build capability on purpose', 'Rotate the successor through sales, operations and finance, with real targets and a manager other than you. Time in another company first often earns them more respect inside yours. Agree in advance what “ready” looks like so the handover date is not a matter of mood.'],
    ['Fairness to family members outside the business', 'Equal is not always fair. Life insurance, property and other assets outside the business, or a staged buy-in can balance what children receive without splitting control of the company among people who do not work in it.'],
    ['Put it in writing with professionals', 'A will, a shareholder agreement and any family settlement should be drafted by a lawyer, and the tax effect of transferring shares or assets checked by your CA before you act. Informal promises are the most common source of later disputes.']
  ], faqs: [
    ['When should I start planning family succession?', 'Earlier than feels necessary. Moving relationships and authority usually takes two to three years, and starting while you are fully active means you can correct mistakes.'],
    ['What if my children do not want the business?', 'Then the plan changes, not fails. Management buyout, an external operator, a partial sale or a strategic sale may fit better, and the same preparation work applies to all of them.']
  ] },
  { slug: 'management-buyout', title: 'Management buyout', read: '6 min read', img: '/images/guide-mbo.jpg', ph: 'Management team around a table', intro: 'Selling to the people who already run the business keeps continuity for customers and staff, if the team and the financing are ready.', assess: 'Management depth and Business Independence scores show whether a buyout is realistic today or a 12 to 24 month project.', sections: [
    ['Who is really “management”?', 'A buyout needs two or three people who already make decisions without you. If every approval still passes your desk, build the team first. The buyout follows.'],
    ['Test the team before you sell to it', 'Step back for a defined period and let the team run sales, operations and finance. Track what happens to customers, cash and staff. A team that has already run the business is far easier to finance and far less risky for you.'],
    ['How it is financed', 'Managers rarely have the full price in cash. Buyouts are usually funded by a mix of the managers’ own money, a loan from a bank or NBFC, and seller financing, where you are paid part of the price over time from the business’s profits. With seller financing you stay financially exposed until the last instalment is paid, so agree security and what happens if payments stop.'],
    ['Pricing it fairly', 'Managers know the business well and may under- or over-value it. An independent valuation keeps the conversation factual and protects the relationship. Agree how working capital, debt and cash on the books are treated on the closing date.'],
    ['Staying involved without staying in charge', 'A defined advisory role, a board seat or a consulting agreement protects your interests while payments are outstanding, and still gives the team real authority. Write down what decisions you keep and for how long.'],
    ['Paperwork and approvals', 'Depending on structure, a buyout can mean a share purchase agreement, transfer of licences and registrations, lender consent on existing loans, and employment terms for the buyers. Your lawyer and CA should plan the structure, because a share sale and an asset or business transfer have different tax and stamp-duty effects.']
  ], faqs: [
    ['Can a management team buy a business without much money?', 'Sometimes, if the business generates enough steady cash to support a bank or NBFC loan and you accept part of the price in instalments. Lenders look closely at the team’s track record running the business.'],
    ['How long does a management buyout take?', 'Building and testing the team often takes 12 to 24 months. The transaction itself, from agreeing terms to signing, is shorter once financing and documents are ready.']
  ] },
  { slug: 'business-valuation', title: 'What your business is worth, and why', read: '7 min read', img: '/images/guide-valuation.jpg', ph: 'Ledgers and a calculator on a desk', intro: 'Owners usually hear a multiple from a friend. Buyers pay for profit that will continue after you leave, and discount what depends on you.', assess: 'The detailed report shows your indicative range and the four factors behind it, so you know what to fix before anyone names a price.', sections: [
    ['Profit is the starting point, not the answer', 'Most valuations of owner-led businesses start from normalised profit: reported profit, adjusted for owner salary and perks, related-party transactions and one-off items. That profit is multiplied by a factor, or the future cash flows are discounted. Either way, the quality of the profit matters as much as the amount.'],
    ['What moves the multiple', 'Recurring or contracted revenue, documented processes, a second line of management, a spread of customers and clean records raise it. Dependence on the owner, one or two customers making up most of sales, and records a buyer cannot verify lower it. Multiples also differ widely by sector, size and the type of buyer.'],
    ['How the Legacy Handover range is calculated', 'Our indicative range estimates profit from your revenue and margin bands, then applies a multiple between about 2.5× and 6× that rises with your Transferability score. It is a planning tool built on our own assumptions, not a market quote, and the report shows each factor so you can see why the range moved.'],
    ['Indicative versus formal', 'An indicative range is useful for planning. A transaction, a share transfer at a regulated price, a tax filing or a loan needs a formal valuation from a registered valuer or other qualified professional, based on verified accounts.'],
    ['What a buyer checks', 'Expect questions on three years of financial statements, tax and GST filings and how they reconcile with the books, customer and supplier contracts, statutory registrations and licences, property documents, employee records and any pending disputes. Gaps here are a common reason prices fall late in a deal.'],
    ['Raising value is mostly preparation', 'The same work that makes a business easier to hand over (records, delegation, contracts) is what buyers pay for. Unlike growth, much of it is within your control and can be done in the year or two before you talk to anyone.']
  ], faqs: [
    ['Is the Legacy Handover value a valuation?', 'No. It is an indicative estimate from your answers and our methodology. Use a registered valuer when you need a formal valuation.'],
    ['Why would two buyers offer different prices?', 'They value different things. A strategic buyer may pay for customers or capacity it can combine with its own, while a financial buyer focuses on stable cash flow and risk.']
  ] },
  { slug: 'preparing-to-step-back', title: 'Preparing to step back', read: '6 min read', img: '/images/guide-prepare.jpg', ph: 'Owner handing a file to a colleague', intro: 'Whether the business goes to family, managers or a buyer, the preparation is the same, and it takes longer than most owners expect.', assess: 'Your readiness plan turns these into dated tasks with impact scores, shareable with your CA if you choose.', sections: [
    ['Make yourself unnecessary, deliberately', 'List everything only you do: key customers, suppliers, banking, pricing, hiring, approvals. Hand over one relationship or decision at a time. Then test it: does the business run normally during a two-week absence?'],
    ['Get the paper in order', 'Audited statements for recent years, GST returns reconciled with the books, contracts signed and filed, licences and registrations current, property papers in order, employee agreements in place. Diligence delays are more often about missing documents than disagreements.'],
    ['Build the second line', 'Name a deputy for operations, sales and finance. Give them real authority and let them make mistakes while you are still there to absorb them. Write down how the important processes work so knowledge is not only in people’s heads.'],
    ['Reduce concentration risk', 'If one customer, supplier or person accounts for a large share of the business, any successor or buyer will see that as risk. Widening the customer base and cross-training staff takes time, so start early.'],
    ['Decide what you want afterwards', 'A full exit, an advisory role or part-time involvement: your preference shapes which paths fit. Owners who decide this early tend to make clearer choices when an opportunity arrives.'],
    ['Bring your advisors in early', 'Your CA, lawyer and banker can flag tax, legal and financing issues while there is still time to fix them cheaply. Sharing a written plan with them keeps everyone working from the same facts.']
  ], faqs: [
    ['How do I know if my business depends too much on me?', 'Ask who customers, suppliers and the bank call when there is a problem, and what happens when you are away for two weeks. The assessment’s Business Independence score measures exactly this.'],
    ['What should I fix first?', 'Usually records and owner dependency, because both take time and affect every succession path. Your readiness plan ranks tasks by their effect on your scores.']
  ] }
];
